import type { Equipment, TrainingLevel } from '../profile/schemas';

export type Muscle =
  'chest' | 'back' | 'shoulders' | 'biceps' | 'triceps' | 'quads' | 'hamstrings' | 'glutes' | 'calves' | 'core';

export type MovementPattern =
  | 'squat'
  | 'hinge'
  | 'lunge'
  | 'push_horizontal'
  | 'push_vertical'
  | 'pull_horizontal'
  | 'pull_vertical'
  | 'arms'
  | 'core';

export interface Exercise {
  id: string;
  name: { fr: string; en: string };
  pattern: MovementPattern;
  primary: Muscle[];
  secondary: Muscle[];
  /** All required. `bodyweight` alone means no equipment. */
  equipment: Equipment[];
  level: TrainingLevel;
  compound: boolean;
  /** Smallest sensible load increase in kg; 0 for bodyweight movements (progress by reps). */
  loadIncrementKg: number;
  cues: { fr: string; en: string };
  mistakes: { fr: string; en: string };
}

export const LEVEL_RANK: Record<TrainingLevel, number> = { beginner: 0, intermediate: 1, advanced: 2 };

type Row = [
  id: string,
  fr: string,
  en: string,
  pattern: MovementPattern,
  primary: Muscle[],
  secondary: Muscle[],
  equipment: Equipment[],
  level: TrainingLevel,
  increment: number,
  cuesFr: string,
  cuesEn: string,
  mistakesFr: string,
  mistakesEn: string,
];

const ROWS: Row[] = [
  [
    'goblet_squat',
    'Goblet squat',
    'Goblet squat',
    'squat',
    ['quads', 'glutes'],
    ['core'],
    ['dumbbells'],
    'beginner',
    2,
    'Haltère contre la poitrine, descendre entre les talons.',
    'Dumbbell at chest, sit between your heels.',
    'Talons qui décollent, dos qui s’arrondit.',
    'Heels lifting, rounding the back.',
  ],
  [
    'bodyweight_squat',
    'Squat au poids du corps',
    'Bodyweight squat',
    'squat',
    ['quads', 'glutes'],
    ['core'],
    ['bodyweight'],
    'beginner',
    0,
    'Pieds largeur d’épaules, poitrine haute.',
    'Feet shoulder-width, chest up.',
    'Genoux qui rentrent vers l’intérieur.',
    'Knees caving in.',
  ],
  [
    'back_squat',
    'Squat barre',
    'Barbell back squat',
    'squat',
    ['quads', 'glutes'],
    ['hamstrings', 'core'],
    ['barbell', 'rack'],
    'intermediate',
    2.5,
    'Gainage fort, descendre sous contrôle.',
    'Brace hard, descend under control.',
    'Charge trop lourde au détriment de l’amplitude.',
    'Too much load at the expense of depth.',
  ],
  [
    'leg_press',
    'Presse à cuisses',
    'Leg press',
    'squat',
    ['quads', 'glutes'],
    [],
    ['machines'],
    'beginner',
    5,
    'Bas du dos collé au dossier.',
    'Keep lower back against the pad.',
    'Verrouiller les genoux en haut.',
    'Locking the knees at the top.',
  ],
  [
    'romanian_deadlift_db',
    'Soulevé de terre roumain haltères',
    'Dumbbell Romanian deadlift',
    'hinge',
    ['hamstrings', 'glutes'],
    ['back'],
    ['dumbbells'],
    'beginner',
    2,
    'Hanches vers l’arrière, dos neutre.',
    'Push hips back, neutral spine.',
    'Plier les genoux comme un squat.',
    'Turning it into a squat.',
  ],
  [
    'romanian_deadlift',
    'Soulevé de terre roumain barre',
    'Barbell Romanian deadlift',
    'hinge',
    ['hamstrings', 'glutes'],
    ['back'],
    ['barbell'],
    'intermediate',
    2.5,
    'Barre proche des jambes.',
    'Keep the bar close to the legs.',
    'Dos arrondi.',
    'Rounded back.',
  ],
  [
    'deadlift',
    'Soulevé de terre',
    'Deadlift',
    'hinge',
    ['hamstrings', 'glutes', 'back'],
    ['quads', 'core'],
    ['barbell'],
    'advanced',
    2.5,
    'Pousser le sol, barre contre les tibias.',
    'Push the floor away, bar against shins.',
    'Tirer avec le dos.',
    'Pulling with the back.',
  ],
  [
    'glute_bridge',
    'Pont fessier',
    'Glute bridge',
    'hinge',
    ['glutes'],
    ['hamstrings'],
    ['bodyweight'],
    'beginner',
    0,
    'Serrer les fessiers en haut.',
    'Squeeze glutes at the top.',
    'Cambrer le bas du dos.',
    'Arching the lower back.',
  ],
  [
    'hip_thrust',
    'Hip thrust',
    'Hip thrust',
    'hinge',
    ['glutes'],
    ['hamstrings'],
    ['barbell', 'bench'],
    'intermediate',
    5,
    'Menton rentré, bassin en rétroversion en haut.',
    'Chin tucked, posterior tilt at the top.',
    'Pousser avec le bas du dos.',
    'Driving with the lower back.',
  ],
  [
    'kettlebell_swing',
    'Swing kettlebell',
    'Kettlebell swing',
    'hinge',
    ['glutes', 'hamstrings'],
    ['core', 'back'],
    ['kettlebell'],
    'intermediate',
    4,
    'Mouvement de hanches, bras relâchés.',
    'Hip snap, relaxed arms.',
    'Lever avec les bras.',
    'Lifting with the arms.',
  ],
  [
    'reverse_lunge',
    'Fente arrière',
    'Reverse lunge',
    'lunge',
    ['quads', 'glutes'],
    ['hamstrings'],
    ['bodyweight'],
    'beginner',
    0,
    'Grand pas en arrière, buste droit.',
    'Big step back, upright torso.',
    'Genou avant qui dépasse fortement.',
    'Front knee collapsing forward.',
  ],
  [
    'db_split_squat',
    'Split squat haltères',
    'Dumbbell split squat',
    'lunge',
    ['quads', 'glutes'],
    [],
    ['dumbbells'],
    'beginner',
    2,
    'Descendre à la verticale.',
    'Drop straight down.',
    'Pieds sur une même ligne.',
    'Feet on a tightrope.',
  ],
  [
    'bulgarian_split_squat',
    'Squat bulgare',
    'Bulgarian split squat',
    'lunge',
    ['quads', 'glutes'],
    [],
    ['dumbbells', 'bench'],
    'intermediate',
    2,
    'Pied arrière posé sur le banc.',
    'Rear foot on the bench.',
    'Pousser avec la jambe arrière.',
    'Pushing with the rear leg.',
  ],
  [
    'push_up',
    'Pompes',
    'Push-up',
    'push_horizontal',
    ['chest', 'triceps'],
    ['shoulders', 'core'],
    ['bodyweight'],
    'beginner',
    0,
    'Corps gainé en planche.',
    'Body in a straight plank.',
    'Hanches qui s’affaissent.',
    'Sagging hips.',
  ],
  [
    'incline_push_up',
    'Pompes inclinées',
    'Incline push-up',
    'push_horizontal',
    ['chest', 'triceps'],
    ['shoulders'],
    ['bodyweight'],
    'beginner',
    0,
    'Mains sur un support stable.',
    'Hands on a stable surface.',
    'Coudes à 90° du corps.',
    'Elbows flared at 90°.',
  ],
  [
    'db_bench_press',
    'Développé couché haltères',
    'Dumbbell bench press',
    'push_horizontal',
    ['chest', 'triceps'],
    ['shoulders'],
    ['dumbbells', 'bench'],
    'beginner',
    2,
    'Omoplates serrées.',
    'Shoulder blades pinched.',
    'Rebondir en bas.',
    'Bouncing at the bottom.',
  ],
  [
    'bench_press',
    'Développé couché barre',
    'Barbell bench press',
    'push_horizontal',
    ['chest', 'triceps'],
    ['shoulders'],
    ['barbell', 'bench', 'rack'],
    'intermediate',
    2.5,
    'Pieds ancrés, barre au bas des pecs.',
    'Feet planted, bar to lower chest.',
    'Fesses qui décollent.',
    'Hips lifting off the bench.',
  ],
  [
    'chest_press_machine',
    'Développé machine',
    'Machine chest press',
    'push_horizontal',
    ['chest', 'triceps'],
    ['shoulders'],
    ['machines'],
    'beginner',
    5,
    'Poignées à hauteur de poitrine.',
    'Handles at chest height.',
    'Épaules qui remontent.',
    'Shrugging shoulders.',
  ],
  [
    'pike_push_up',
    'Pompes piquées',
    'Pike push-up',
    'push_vertical',
    ['shoulders', 'triceps'],
    [],
    ['bodyweight'],
    'intermediate',
    0,
    'Hanches hautes, tête entre les mains.',
    'Hips high, head between hands.',
    'Coudes trop écartés.',
    'Elbows flaring wide.',
  ],
  [
    'db_shoulder_press',
    'Développé épaules haltères',
    'Dumbbell shoulder press',
    'push_vertical',
    ['shoulders', 'triceps'],
    [],
    ['dumbbells'],
    'beginner',
    2,
    'Gainage, pas de cambrure.',
    'Brace, avoid arching.',
    'Cambrer pour pousser.',
    'Leaning back to push.',
  ],
  [
    'overhead_press',
    'Développé militaire',
    'Overhead press',
    'push_vertical',
    ['shoulders', 'triceps'],
    ['core'],
    ['barbell', 'rack'],
    'intermediate',
    2.5,
    'Fessiers serrés, barre au-dessus du milieu du pied.',
    'Glutes tight, bar over mid-foot.',
    'Cambrure excessive.',
    'Excessive arch.',
  ],
  [
    'band_row',
    'Tirage élastique',
    'Band row',
    'pull_horizontal',
    ['back'],
    ['biceps'],
    ['bands'],
    'beginner',
    0,
    'Tirer les coudes vers l’arrière.',
    'Drive elbows back.',
    'Hausser les épaules.',
    'Shrugging.',
  ],
  [
    'db_row',
    'Rowing haltère',
    'One-arm dumbbell row',
    'pull_horizontal',
    ['back'],
    ['biceps'],
    ['dumbbells', 'bench'],
    'beginner',
    2,
    'Dos plat, coude vers la hanche.',
    'Flat back, elbow to hip.',
    'Tourner le buste.',
    'Twisting the torso.',
  ],
  [
    'barbell_row',
    'Rowing barre',
    'Barbell row',
    'pull_horizontal',
    ['back'],
    ['biceps', 'hamstrings'],
    ['barbell'],
    'intermediate',
    2.5,
    'Buste incliné stable.',
    'Stable hinged torso.',
    'Utiliser l’élan.',
    'Using momentum.',
  ],
  [
    'seated_cable_row',
    'Tirage horizontal poulie',
    'Seated cable row',
    'pull_horizontal',
    ['back'],
    ['biceps'],
    ['cable'],
    'beginner',
    5,
    'Poitrine haute, omoplates serrées.',
    'Chest up, squeeze shoulder blades.',
    'Se balancer.',
    'Rocking back and forth.',
  ],
  [
    'inverted_row',
    'Tirage australien',
    'Inverted row',
    'pull_horizontal',
    ['back'],
    ['biceps', 'core'],
    ['pullup_bar'],
    'beginner',
    0,
    'Corps droit, poitrine vers la barre.',
    'Straight body, chest to bar.',
    'Hanches qui tombent.',
    'Hips dropping.',
  ],
  [
    'lat_pulldown',
    'Tirage vertical',
    'Lat pulldown',
    'pull_vertical',
    ['back'],
    ['biceps'],
    ['cable'],
    'beginner',
    5,
    'Tirer vers le haut de la poitrine.',
    'Pull to upper chest.',
    'Tirer derrière la nuque.',
    'Pulling behind the neck.',
  ],
  [
    'pull_up',
    'Tractions',
    'Pull-up',
    'pull_vertical',
    ['back'],
    ['biceps', 'core'],
    ['pullup_bar'],
    'intermediate',
    0,
    'Partir bras tendus, menton au-dessus de la barre.',
    'Start from dead hang, chin over bar.',
    'Demi-amplitude.',
    'Half reps.',
  ],
  [
    'band_pulldown',
    'Tirage vertical élastique',
    'Band pulldown',
    'pull_vertical',
    ['back'],
    ['biceps'],
    ['bands'],
    'beginner',
    0,
    'Élastique fixé en hauteur, coudes vers les côtes.',
    'Band anchored high, elbows to ribs.',
    'Bras qui font tout le travail.',
    'Arms doing all the work.',
  ],
  [
    'db_curl',
    'Curl haltères',
    'Dumbbell curl',
    'arms',
    ['biceps'],
    [],
    ['dumbbells'],
    'beginner',
    1,
    'Coudes fixes.',
    'Elbows fixed.',
    'Balancer le buste.',
    'Swinging the torso.',
  ],
  [
    'band_curl',
    'Curl élastique',
    'Band curl',
    'arms',
    ['biceps'],
    [],
    ['bands'],
    'beginner',
    0,
    'Contrôler la descente.',
    'Control the way down.',
    'Relâcher d’un coup.',
    'Letting it snap back.',
  ],
  [
    'bench_dip',
    'Dips sur banc',
    'Bench dip',
    'arms',
    ['triceps'],
    ['chest', 'shoulders'],
    ['bodyweight'],
    'beginner',
    0,
    'Épaules basses, amplitude confortable.',
    'Shoulders down, comfortable range.',
    'Descendre trop bas.',
    'Going too deep.',
  ],
  [
    'cable_triceps_pushdown',
    'Extension triceps poulie',
    'Cable triceps pushdown',
    'arms',
    ['triceps'],
    [],
    ['cable'],
    'beginner',
    2.5,
    'Coudes collés au corps.',
    'Elbows pinned to your sides.',
    'Pencher le buste sur la charge.',
    'Leaning over the weight.',
  ],
  [
    'plank',
    'Gainage planche',
    'Plank',
    'core',
    ['core'],
    ['shoulders'],
    ['bodyweight'],
    'beginner',
    0,
    'Corps aligné, respirer.',
    'Body aligned, keep breathing.',
    'Bloquer la respiration.',
    'Holding your breath.',
  ],
  [
    'dead_bug',
    'Dead bug',
    'Dead bug',
    'core',
    ['core'],
    [],
    ['bodyweight'],
    'beginner',
    0,
    'Bas du dos collé au sol.',
    'Lower back glued to the floor.',
    'Aller trop vite.',
    'Rushing the reps.',
  ],
  [
    'hanging_knee_raise',
    'Relevés de genoux suspendu',
    'Hanging knee raise',
    'core',
    ['core'],
    [],
    ['pullup_bar'],
    'intermediate',
    0,
    'Enrouler le bassin.',
    'Curl the pelvis up.',
    'Se balancer.',
    'Swinging.',
  ],
];

export const EXERCISES: readonly Exercise[] = ROWS.map(
  ([id, fr, en, pattern, primary, secondary, equipment, level, increment, cuesFr, cuesEn, mistakesFr, mistakesEn]) => ({
    id,
    name: { fr, en },
    pattern,
    primary,
    secondary,
    equipment,
    level,
    compound: pattern !== 'arms' && pattern !== 'core',
    loadIncrementKg: increment,
    cues: { fr: cuesFr, en: cuesEn },
    mistakes: { fr: mistakesFr, en: mistakesEn },
  }),
);

const BY_ID = new Map(EXERCISES.map((e) => [e.id, e]));

export function getExercise(id: string): Exercise | undefined {
  return BY_ID.get(id);
}

export function isAvailable(exercise: Exercise, equipment: readonly Equipment[]): boolean {
  return exercise.equipment.every((e) => e === 'bodyweight' || equipment.includes(e));
}

/**
 * Easier variants (W-5, D-037): curated relations between catalogue ids, never inferred from a
 * name. An easier variant keeps the movement (same pattern, or the same main muscles for an arm
 * or core exercise) with less load, more guidance (machine, cable) or less technique; its level
 * is never above the exercise's. An exercise without an entry has no known easier variant: none
 * is invented. Harder variants are the inverse relation (`harderVariants`). [relire]
 */
export const EASIER_VARIANTS: Readonly<Record<string, readonly string[]>> = {
  back_squat: ['goblet_squat', 'leg_press'],
  goblet_squat: ['bodyweight_squat'],
  deadlift: ['romanian_deadlift', 'romanian_deadlift_db'],
  romanian_deadlift: ['romanian_deadlift_db'],
  romanian_deadlift_db: ['glute_bridge'],
  hip_thrust: ['glute_bridge'],
  kettlebell_swing: ['romanian_deadlift_db', 'glute_bridge'],
  bulgarian_split_squat: ['db_split_squat', 'reverse_lunge'],
  db_split_squat: ['reverse_lunge'],
  push_up: ['incline_push_up'],
  bench_press: ['db_bench_press', 'chest_press_machine'],
  db_bench_press: ['chest_press_machine'],
  overhead_press: ['db_shoulder_press'],
  pike_push_up: ['db_shoulder_press'],
  barbell_row: ['db_row', 'seated_cable_row'],
  db_row: ['seated_cable_row', 'band_row'],
  inverted_row: ['band_row'],
  pull_up: ['lat_pulldown', 'band_pulldown', 'inverted_row'],
  lat_pulldown: ['band_pulldown'],
  hanging_knee_raise: ['dead_bug'],
  bench_dip: ['cable_triceps_pushdown'],
  db_curl: ['band_curl'],
};

/** Easier variants of an exercise, in the catalogue's order of preference. */
export function easierVariants(id: string): Exercise[] {
  return (EASIER_VARIANTS[id] ?? []).map((v) => BY_ID.get(v)).filter((e): e is Exercise => !!e);
}

/** Harder variants: the exercises that list this one as an easier variant. */
export function harderVariants(id: string): Exercise[] {
  return Object.entries(EASIER_VARIANTS)
    .filter(([, easier]) => easier.includes(id))
    .map(([harder]) => BY_ID.get(harder))
    .filter((e): e is Exercise => !!e)
    .sort((a, b) => a.id.localeCompare(b.id));
}
