/**
 * Workout Coach foundation (W-1, docs/TRAINING_ARCHITECTURE.md §2, D-031): published program
 * versions and immutable prescriptions, so "what was planned" is never recomputed from the current
 * profile. Pure functions: ids and timestamps come from the caller.
 *
 * Kinds of data (D-031 B), never mixed:
 * - FACT: recorded directly (sets done, loads, reps, completion time);
 * - USER_REPORTED: declared by the user (difficulty, reasons, notes, fatigue);
 * - DERIVED: computed and recomputable (gap planned/actual, trends, records), never stored;
 * - RECOMMENDATION: produced by the engine (program versions, prescriptions, proposed loads).
 */
import type { Equipment, GoalType, TrainingLevel, TrainingProfile } from '../profile/schemas';
import { addDays, type IsoDate } from '../shared/dates';
import type { AdaptedSession, SessionVariant } from './adapt';
import { generateWorkoutPlan, type SessionFocus, type SetUnit, type WorkoutTemplate } from './engine';
import { getExercise } from './exercises';
import type { LegacyProgressionAction, ProgressionAction, ProgressionConfidence } from './progression';
import type { ReplacementReason } from './replacement';

export type DataKind = 'fact' | 'user_reported' | 'derived' | 'recommendation';

/** Kind of every stored training field. Derived values have no column: they are recomputed. */
export const TRAINING_DATA_KINDS = {
  'training_programs.*': 'recommendation',
  'workout_sessions.focus': 'recommendation',
  'workout_sessions.planned_minutes': 'recommendation',
  'workout_sessions.purpose': 'recommendation',
  'workout_sessions.adapted_minutes': 'recommendation',
  'workout_sessions.adaptation_reason': 'recommendation',
  'workout_sessions.variant': 'fact',
  'workout_sessions.status': 'fact',
  'workout_sessions.started_at': 'fact',
  'workout_sessions.completed_at': 'fact',
  'workout_sessions.rescheduled_to': 'fact',
  'workout_sessions.outcome_reason': 'user_reported',
  'workout_sessions.replaced_by': 'user_reported',
  'workout_sessions.difficulty': 'user_reported',
  'workout_sessions.notes': 'user_reported',
  'planned_exercises.*': 'recommendation',
  'exercise_logs.reps': 'fact',
  'exercise_logs.seconds': 'fact',
  'exercise_logs.load_kg': 'fact',
  'exercise_logs.rpe': 'user_reported',
  'exercise_logs.notes': 'user_reported',
  'exercise_substitutions.to_exercise_id': 'fact',
  'exercise_substitutions.reason': 'user_reported',
  'adjustments.status': 'user_reported',
  'daily_checkins.fatigue': 'user_reported',
} as const satisfies Record<string, Exclude<DataKind, 'derived'>>;

/** Why a session or an exercise is prescribed (structured; the sentence is generated by the app). */
export const TRAINING_PURPOSES = [
  'strength',
  'hypertrophy',
  'muscular_endurance',
  'technique',
  'maintenance',
  'recovery',
  'progression',
] as const;
export type TrainingPurpose = (typeof TRAINING_PURPOSES)[number];

/** Felt difficulty, in words for the user; stored 1–5 (`workout_sessions.difficulty`). No RPE asked. */
export const DIFFICULTY_LEVELS = ['very_easy', 'easy', 'ok', 'hard', 'very_hard'] as const;
export type DifficultyLevel = (typeof DIFFICULTY_LEVELS)[number];

export function difficultyScore(level: DifficultyLevel): number {
  return DIFFICULTY_LEVELS.indexOf(level) + 1;
}

export function difficultyLevel(score: number): DifficultyLevel | null {
  return Number.isInteger(score) ? (DIFFICULTY_LEVELS[score - 1] ?? null) : null;
}

/** Cycle length (D-031): at its end a light week may be proposed, never imposed. */
export const DEFAULT_CYCLE_WEEKS = 6;

/** What the engine was given when it generated a version (frozen at publication). */
export interface ProgramParams {
  engineVersion: number;
  goal: GoalType;
  split: SessionFocus[];
  sessionsPerWeek: number;
  sessionMinutes: number;
  level: TrainingLevel;
  equipment: Equipment[];
  excludedExerciseIds: string[];
  /**
   * Exercises rotated at an end-of-cycle evolution the user accepted (W-5, D-037). Present only
   * when not empty, so the versions published before keep the same parameters.
   */
  rotatedExerciseIds?: string[];
}

export type ProgramSource = 'engine' | 'reconstructed';
export type ProgramStatus = 'active' | 'superseded' | 'ended';

/** One row of `training_programs`: a published, immutable program version. */
export interface ProgramVersion {
  id: string;
  /** "Program X" across its versions. */
  lineageId: string;
  version: number;
  source: ProgramSource;
  status: ProgramStatus;
  reasonKey: string;
  adjustmentId: string | null;
  /** Null for a reconstructed program: what was planned before W-1 is unknown. */
  params: ProgramParams | null;
  cycleWeeks: number | null;
  effectiveFrom: IsoDate;
  effectiveTo: IsoDate | null;
  publishedAt: string;
}

/** One row of `planned_exercises`: what was prescribed, immutable. */
export interface PlannedExercise {
  id: string;
  sessionId: string;
  variant: SessionVariant;
  position: number;
  exerciseId: string;
  sets: number;
  repsMin: number;
  repsMax: number;
  unit: SetUnit;
  restSeconds: number;
  targetRpe: number | null;
  /** Null when the engine had nothing to base a load on (never guessed). */
  targetLoadKg: number | null;
  /** W-4 actions; rows prescribed before W-4 keep their legacy action (read, never produced). */
  progressionAction: ProgressionAction | LegacyProgressionAction | null;
  progressionReason: string | null;
  /** Reps (or seconds) to aim for in each set (W-4); null when the engine had no basis. */
  targetReps: number | null;
  progressionConfidence: ProgressionConfidence | null;
  /** Facts the reason is told with ("2 séances", "12 reps"): numbers from the evidence only. */
  progressionParams: Record<string, number | string> | null;
  purpose: TrainingPurpose;
  purposeTarget: string | null;
  /** When this row was prescribed (the full session, or later the adaptation of the day). */
  prescribedAt: string;
}

/**
 * engine: prescribed by a program version · off_plan: done on a day without a planned session ·
 * unknown: recorded before W-1, its prescription was never stored.
 */
export type PrescriptionSource = 'engine' | 'off_plan' | 'unknown';

/** The prescription part of a `workout_sessions` row, plus its planned exercises. */
export interface PrescribedSession {
  id: string;
  programId: string;
  date: IsoDate;
  sessionIndex: number;
  focus: SessionFocus;
  plannedMinutes: number;
  purpose: TrainingPurpose;
  prescriptionSource: 'engine';
  prescribedAt: string;
  /** Adaptation of the day (short, light…), with its own exercises below. */
  adaptedMinutes: number | null;
  adaptationReason: string | null;
  /**
   * The structural decision this prescription follows (W-5, D-037: reduced volume, easier
   * variant, restart); absent for a normal prescription.
   */
  adjustmentId?: string | null;
  exercises: PlannedExercise[];
}

type TrainingInput = Pick<
  TrainingProfile,
  'level' | 'sessionsPerWeek' | 'sessionMinutes' | 'equipment' | 'refusedExerciseIds'
> & { rotatedExerciseIds?: readonly string[] };

export function deepFreeze<T>(value: T): T {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const v of Object.values(value)) deepFreeze(v);
  }
  return value;
}

const sorted = (list: readonly string[]) => [...list].sort();

/** The parameters a version would be generated from today. Copies: never shares the profile's arrays. */
export function programParams(goal: GoalType, training: TrainingInput): ProgramParams {
  const plan = generateWorkoutPlan({ goal, training });
  return {
    engineVersion: plan.engineVersion,
    goal,
    split: plan.sessions.map((s) => s.focus),
    sessionsPerWeek: training.sessionsPerWeek,
    sessionMinutes: training.sessionMinutes,
    level: training.level,
    equipment: sorted(training.equipment) as Equipment[],
    excludedExerciseIds: sorted(training.refusedExerciseIds),
    ...(training.rotatedExerciseIds?.length ? { rotatedExerciseIds: sorted(training.rotatedExerciseIds) } : {}),
  };
}

/** True when the profile no longer matches the active version: a new version must be published. */
export function programParamsChanged(active: ProgramVersion, goal: GoalType, training: TrainingInput): boolean {
  if (!active.params) return true;
  return JSON.stringify(active.params) !== JSON.stringify(programParams(goal, training));
}

/**
 * Publishes a new version. The previous active version is closed (superseded the day before),
 * never edited otherwise; the new one continues its lineage with the next version number.
 */
export function publishProgram(input: {
  id: string;
  /** Used when there is no engine version to continue (first program). */
  lineageId: string;
  previous: ProgramVersion | null;
  goal: GoalType;
  training: TrainingInput;
  effectiveFrom: IsoDate;
  reasonKey: string;
  adjustmentId?: string | null;
  publishedAt: string;
  cycleWeeks?: number;
  /** Next free number of the lineage when known (W-2); defaults to the previous version + 1. */
  version?: number;
}): { published: ProgramVersion; closed: ProgramVersion | null } {
  const { previous } = input;
  const continues = previous?.source === 'engine';
  const published: ProgramVersion = {
    id: input.id,
    lineageId: continues ? previous.lineageId : input.lineageId,
    version: input.version ?? (continues ? previous.version + 1 : 1),
    source: 'engine',
    status: 'active',
    reasonKey: input.reasonKey,
    adjustmentId: input.adjustmentId ?? null,
    params: programParams(input.goal, input.training),
    cycleWeeks: input.cycleWeeks ?? DEFAULT_CYCLE_WEEKS,
    effectiveFrom: input.effectiveFrom,
    effectiveTo: null,
    publishedAt: input.publishedAt,
  };
  let closed: ProgramVersion | null = null;
  if (previous && previous.status === 'active') {
    const dayBefore = addDays(input.effectiveFrom, -1);
    closed = {
      ...previous,
      status: 'superseded',
      effectiveTo: dayBefore < previous.effectiveFrom ? previous.effectiveFrom : dayBefore,
    };
  }
  return { published: deepFreeze(published), closed: closed ? deepFreeze(closed) : null };
}

/** The purpose of a session, from the goal frozen in the version (a light day is recovery). */
export function sessionPurpose(goal: GoalType, variant: SessionVariant = 'full'): TrainingPurpose {
  if (variant === 'light') return 'recovery';
  if (variant === 'short') return 'muscular_endurance';
  switch (goal) {
    case 'performance':
      return 'strength';
    case 'muscle_gain':
    case 'recomposition':
      return 'hypertrophy';
    case 'fitness':
      return 'muscular_endurance';
    default:
      // Fat loss, weight loss, maintenance: keep the muscle and the strength already there.
      return 'maintenance';
  }
}

function exercisePurpose(
  exerciseId: string,
  session: TrainingPurpose,
  level: TrainingLevel,
): { purpose: TrainingPurpose; purposeTarget: string | null } {
  const exercise = getExercise(exerciseId);
  if (!exercise) return { purpose: session, purposeTarget: null };
  // A beginner first learns the big movements.
  const purpose = level === 'beginner' && exercise.compound && session !== 'recovery' ? 'technique' : session;
  const purposeTarget = purpose === 'hypertrophy' ? (exercise.primary[0] ?? null) : exercise.pattern;
  return { purpose, purposeTarget };
}

/** Proposed load for an exercise, when the progression engine had history to base it on. */
export interface ProposedLoad {
  loadKg: number | null;
  action: ProgressionAction | LegacyProgressionAction;
  reasonKey: string;
  targetReps?: number;
  confidence?: ProgressionConfidence;
  params?: Record<string, number | string>;
}

function plannedRows(input: {
  sessionId: string;
  variant: SessionVariant;
  exercises: WorkoutTemplate['exercises'];
  purpose: TrainingPurpose;
  level: TrainingLevel;
  loads: Record<string, ProposedLoad>;
  prescribedAt: string;
  ids: (variant: SessionVariant, position: number) => string;
}): PlannedExercise[] {
  return input.exercises.map((e, position) => {
    const load = input.loads[e.exerciseId];
    return {
      id: input.ids(input.variant, position),
      sessionId: input.sessionId,
      variant: input.variant,
      position,
      exerciseId: e.exerciseId,
      sets: e.sets,
      repsMin: e.repsMin,
      repsMax: e.repsMax,
      unit: e.unit,
      restSeconds: e.restSeconds,
      targetRpe: e.targetRpe,
      targetLoadKg: load?.loadKg ?? null,
      progressionAction: load?.action ?? null,
      progressionReason: load ? load.reasonKey : null,
      // A goal outside the range of this row (a variant with its own range) is brought back into it.
      targetReps: load?.targetReps !== undefined ? Math.max(e.repsMin, Math.min(e.repsMax, load.targetReps)) : null,
      progressionConfidence: load?.confidence ?? null,
      progressionParams: load?.params && Object.keys(load.params).length > 0 ? { ...load.params } : null,
      // An easier variant prepares the exercise it stands in for (W-5, D-037).
      ...(e.standsFor
        ? { purpose: 'progression' as const, purposeTarget: e.standsFor }
        : exercisePurpose(e.exerciseId, input.purpose, input.level)),
      prescribedAt: input.prescribedAt,
    };
  });
}

/**
 * Freezes the prescription of one planned session from a program version and its template. Every
 * value is copied: changing the profile, the template or the program afterwards changes nothing.
 */
export function prescribeSession(input: {
  sessionId: string;
  program: ProgramVersion;
  template: WorkoutTemplate;
  date: IsoDate;
  sessionIndex: number;
  prescribedAt: string;
  loads?: Record<string, ProposedLoad>;
  /** Id of each planned row (deterministic in the app: same session, variant and position → same id). */
  ids: (variant: SessionVariant, position: number) => string;
  /** Structural decision the template was shaped by (W-5), if any. */
  adjustmentId?: string | null;
}): PrescribedSession {
  const { program } = input;
  if (program.source !== 'engine' || !program.params) {
    throw new Error('prescribeSession: a reconstructed program prescribes nothing');
  }
  const purpose = sessionPurpose(program.params.goal);
  return deepFreeze({
    id: input.sessionId,
    programId: program.id,
    date: input.date,
    sessionIndex: input.sessionIndex,
    focus: input.template.focus,
    plannedMinutes: input.template.estimatedMinutes,
    purpose,
    prescriptionSource: 'engine' as const,
    prescribedAt: input.prescribedAt,
    adaptedMinutes: null,
    adaptationReason: null,
    ...(input.adjustmentId ? { adjustmentId: input.adjustmentId } : {}),
    exercises: plannedRows({
      sessionId: input.sessionId,
      variant: 'full',
      exercises: input.template.exercises,
      purpose,
      level: program.params.level,
      loads: input.loads ?? {},
      prescribedAt: input.prescribedAt,
      ids: input.ids,
    }),
  });
}

/**
 * Records the adaptation of the day as new rows under its own variant: the full prescription is
 * kept as it was given. A variant already prescribed is returned unchanged (never rewritten).
 */
export function adaptPrescription(input: {
  session: PrescribedSession;
  program: Pick<ProgramVersion, 'params'> | null;
  adapted: AdaptedSession;
  /** Duration announced to the user (the Daily Coach's), not the circuit's estimate. */
  minutes: number;
  reasonKey: string;
  prescribedAt: string;
  ids: (variant: SessionVariant, position: number) => string;
  /** Loads carried over from the full prescription for the same exercises (never guessed). */
  loads?: Record<string, ProposedLoad>;
}): PrescribedSession {
  const { session, adapted } = input;
  if (adapted.variant === 'full' || session.exercises.some((e) => e.variant === adapted.variant)) return session;
  const purpose = sessionPurpose(input.program?.params?.goal ?? 'maintenance', adapted.variant);
  // One slot for the adaptation of the day (D-034), minutes and reason always of the same variant
  // (W-7.1: never light's reason with short's rows). The short version owns it when there is one:
  // its minutes are the user's, the rows cannot give them back; light is the estimate of its rows.
  const owns = session.adaptedMinutes === null || adapted.variant === 'short';
  return deepFreeze({
    ...session,
    adaptedMinutes: owns ? input.minutes : session.adaptedMinutes,
    adaptationReason: owns ? input.reasonKey : session.adaptationReason,
    exercises: [
      ...session.exercises,
      ...plannedRows({
        sessionId: session.id,
        variant: adapted.variant,
        exercises: adapted.exercises,
        purpose,
        level: input.program?.params?.level ?? 'beginner',
        loads: input.loads ?? {},
        prescribedAt: input.prescribedAt,
        ids: input.ids,
      }),
    ],
  });
}

/** A session as recorded (any origin), seen from the program it belongs to. */
export interface RecordedSession {
  id: string;
  date: IsoDate;
  sessionIndex: number | null;
  programId: string | null;
  prescriptionSource: PrescriptionSource | null;
}

/**
 * The program that groups the sessions recorded before W-1 (`attach_reconstructed_training_history`
 * does the same on the server). It knows no parameter: nothing is invented.
 */
export function reconstructedProgram(input: {
  id: string;
  lineageId: string;
  sessions: readonly RecordedSession[];
  publishedAt: string;
}): ProgramVersion | null {
  const legacy = input.sessions.filter((s) => s.programId === null && s.prescriptionSource === null);
  if (legacy.length === 0) return null;
  return deepFreeze({
    id: input.id,
    lineageId: input.lineageId,
    version: 1,
    source: 'reconstructed' as const,
    status: 'ended' as const,
    reasonKey: 'program.reason.reconstructed',
    adjustmentId: null,
    params: null,
    cycleWeeks: null,
    effectiveFrom: legacy.map((s) => s.date).sort()[0],
    effectiveTo: null,
    publishedAt: input.publishedAt,
  });
}

/** Attaches legacy sessions (no program, no source) once; others are left untouched. */
export function attachLegacySessions<T extends RecordedSession>(sessions: readonly T[], program: ProgramVersion): T[] {
  return sessions.map((s) =>
    s.programId === null && s.prescriptionSource === null
      ? { ...s, programId: program.id, prescriptionSource: 'unknown' as const }
      : s,
  );
}

/** What was planned for a session, or "unknown" when it was never stored. */
export type PlannedView =
  | { status: 'known'; variant: SessionVariant; exercises: PlannedExercise[] }
  | { status: 'unknown' }
  | { status: 'none' };

export function plannedFor(
  session: Pick<RecordedSession, 'prescriptionSource'>,
  planned: readonly PlannedExercise[],
  variant: SessionVariant = 'full',
): PlannedView {
  if (session.prescriptionSource === 'unknown' || session.prescriptionSource === null) return { status: 'unknown' };
  if (session.prescriptionSource === 'off_plan') return { status: 'none' };
  const rows = planned.filter((p) => p.variant === variant).sort((a, b) => a.position - b.position);
  return rows.length > 0 ? { status: 'known', variant, exercises: rows } : { status: 'unknown' };
}

/**
 * The planned exercise a set belongs to: the exercise itself, or the prescribed one it replaced
 * (`exercise_logs.planned_exercise_id`). Null for an exercise added outside the prescription.
 */
export function plannedExerciseFor(
  planned: readonly PlannedExercise[],
  exerciseId: string,
  swaps: readonly { fromId: string; toId: string; reason?: ReplacementReason }[] = [],
): PlannedExercise | null {
  const direct = planned.find((p) => p.exerciseId === exerciseId);
  if (direct) return direct;
  const swap = swaps.find((s) => s.toId === exerciseId);
  return swap ? (planned.find((p) => p.exerciseId === swap.fromId) ?? null) : null;
}
