-- Workout Coach Engine, W-1: persistent foundation (docs/DECISIONS.md D-030, D-031;
-- docs/TRAINING_ARCHITECTURE.md §2).
--
-- Planned vs actual, without recomputing the past from the current profile:
--   training_programs (one row = one published, immutable program version)
--     └─ workout_sessions (extended: the prescribed session, then what happened)
--          ├─ planned_exercises (new: the prescription, immutable, one set of rows per variant)
--          │    ├─ exercise_logs (extended: the sets actually done, linked to the prescription)
--          │    └─ exercise_substitutions (extended: the replacement and the declared reason)
--          └─ difficulty (new column: declared by the user, 1–5)
--
-- Immutability: a published version or a prescription is never rewritten (triggers below). The user
-- can still delete their data (Privacy Center, account deletion): erasure is not a rewrite.
-- Existing tables are extended rather than doubled. `workout_plans` (never written by the app) is
-- left in place and unused; dropping it is a separate, later decision.

-- ---------------------------------------------------------------------------
-- 1. Program versions
-- ---------------------------------------------------------------------------

create table public.training_programs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  -- "Program X" across its versions (v1 → adaptation → v2 share the lineage).
  lineage_id uuid not null,
  version integer not null check (version >= 1),
  -- engine: generated by the training engine; reconstructed: groups sessions recorded before W-1.
  source text not null check (source in ('engine', 'reconstructed')),
  status text not null check (status in ('active', 'superseded', 'ended')),
  -- Why this version exists (structured key, the text is generated by the app).
  reason_key text not null check (reason_key ~ '^[a-z0-9_.]{1,80}$'),
  -- Decision of the Adaptation Engine that produced this version (soft reference: kept even if the
  -- decision is deleted with the journey category).
  adjustment_id uuid,
  -- Parameters the engine used, frozen at publication. Unknown (null) for a reconstructed program.
  engine_version integer check (engine_version >= 1),
  goal text check (goal in ('fat_loss', 'weight_loss', 'muscle_gain', 'recomposition', 'maintenance', 'fitness', 'performance')),
  split text[] check (split <@ array['full_a', 'full_b', 'upper', 'lower']::text[] and cardinality(split) between 1 and 6),
  sessions_per_week smallint check (sessions_per_week between 1 and 6),
  session_minutes smallint check (session_minutes between 10 and 180),
  level text check (level in ('beginner', 'intermediate', 'advanced')),
  equipment text[] check (equipment <@ array['bodyweight', 'dumbbells', 'barbell', 'bench', 'rack', 'cable', 'machines', 'kettlebell', 'bands', 'pullup_bar']::text[]),
  -- Exercises the user refused at publication (they shape the generated sessions).
  excluded_exercise_ids text[] check (
    cardinality(excluded_exercise_ids) <= 200 and array_to_string(excluded_exercise_ids, ',') ~ '^[a-z0-9_:,-]*$'
  ),
  cycle_weeks smallint check (cycle_weeks between 1 and 12),
  effective_from date not null,
  effective_to date,
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, lineage_id, version),
  check (effective_to is null or effective_to >= effective_from),
  -- An engine version always carries the parameters it was generated from.
  check (
    source <> 'engine'
    or (engine_version is not null and goal is not null and split is not null and sessions_per_week is not null
        and session_minutes is not null and level is not null and equipment is not null
        and excluded_exercise_ids is not null)
  ),
  -- A reconstructed program never pretends to know what was planned (no invented prescription).
  check (
    source <> 'reconstructed'
    or (engine_version is null and goal is null and split is null and sessions_per_week is null
        and session_minutes is null and level is null and equipment is null and excluded_exercise_ids is null
        and cycle_weeks is null
        and adjustment_id is null and status = 'ended')
  )
);

create unique index training_programs_one_active on public.training_programs (user_id) where status = 'active';
create unique index training_programs_one_reconstructed on public.training_programs (user_id) where source = 'reconstructed';
create index training_programs_sync_idx on public.training_programs (user_id, updated_at);
create index training_programs_lineage_idx on public.training_programs (user_id, lineage_id);

-- A published version is immutable. Only its lifecycle moves forward:
-- status active → superseded | ended (never back), effective_to null → a date (once).
create or replace function public.training_programs_immutable() returns trigger
language plpgsql set search_path = '' as $$
begin
  if (new.id, new.user_id, new.lineage_id, new.version, new.source, new.reason_key, new.adjustment_id,
      new.engine_version, new.goal, new.split, new.sessions_per_week, new.session_minutes, new.level,
      new.equipment, new.excluded_exercise_ids, new.cycle_weeks, new.effective_from, new.published_at, new.created_at)
     is distinct from
     (old.id, old.user_id, old.lineage_id, old.version, old.source, old.reason_key, old.adjustment_id,
      old.engine_version, old.goal, old.split, old.sessions_per_week, old.session_minutes, old.level,
      old.equipment, old.excluded_exercise_ids, old.cycle_weeks, old.effective_from, old.published_at, old.created_at) then
    raise exception 'training_programs: a published program version is immutable (publish a new version)'
      using errcode = 'check_violation';
  end if;
  if new.status is distinct from old.status and not (old.status = 'active' and new.status in ('superseded', 'ended')) then
    raise exception 'training_programs: status % cannot become %', old.status, new.status using errcode = 'check_violation';
  end if;
  if old.effective_to is not null and new.effective_to is distinct from old.effective_to then
    raise exception 'training_programs: effective_to is already set' using errcode = 'check_violation';
  end if;
  return new;
end;
$$;

create trigger training_programs_immutable before update on public.training_programs
  for each row execute function public.training_programs_immutable();

-- ---------------------------------------------------------------------------
-- 2. Sessions: the prescribed session, then what happened
-- ---------------------------------------------------------------------------

alter table public.workout_sessions
  add column program_id uuid references public.training_programs (id),
  add column focus text check (focus in ('full_a', 'full_b', 'upper', 'lower', 'custom')),
  -- Duration of the full prescription (minutes).
  add column planned_minutes smallint check (planned_minutes between 5 and 180),
  -- Why this session exists (structured; the app writes the sentence).
  add column purpose text check (purpose in (
    'strength', 'hypertrophy', 'muscular_endurance', 'technique', 'maintenance', 'recovery', 'progression'
  )),
  -- engine: prescribed by a program version · off_plan: done on a day without a planned session ·
  -- unknown: recorded before W-1, the prescription was never stored and stays unknown.
  add column prescription_source text check (prescription_source in ('engine', 'off_plan', 'unknown')),
  add column prescribed_at timestamptz,
  -- Adaptation of the day (short, light…), decided before the session; the adapted prescription
  -- itself lives in planned_exercises under its own variant.
  add column adapted_minutes smallint check (adapted_minutes between 5 and 180),
  add column adaptation_reason text check (adaptation_reason ~ '^[a-z0-9_.]{1,80}$'),
  add column rescheduled_to date,
  -- Declared by the user at the end of the session: 1 very easy … 5 very hard.
  add column difficulty smallint check (difficulty between 1 and 5);

alter table public.workout_sessions drop constraint if exists workout_sessions_status_check;
alter table public.workout_sessions add constraint workout_sessions_status_check
  check (status in ('planned', 'in_progress', 'completed', 'skipped', 'rescheduled', 'replaced', 'superseded'));
alter table public.workout_sessions add constraint workout_sessions_rescheduled_to_status
  check (rescheduled_to is null or status = 'rescheduled');
alter table public.workout_sessions add constraint workout_sessions_engine_prescription
  check (prescription_source is distinct from 'engine'
         or (program_id is not null and prescribed_at is not null and focus is not null and planned_minutes is not null));
alter table public.workout_sessions add constraint workout_sessions_unknown_prescription
  check (prescription_source is distinct from 'unknown'
         or (prescribed_at is null and focus is null and planned_minutes is null and purpose is null));

create index workout_sessions_program_idx on public.workout_sessions (program_id);

-- A session can only belong to one of the user's own programs.
create policy workout_sessions_own_program on public.workout_sessions as restrictive for all to authenticated
  using (program_id is null or exists (select 1 from public.training_programs p where p.id = program_id and p.user_id = (select auth.uid())))
  with check (program_id is null or exists (select 1 from public.training_programs p where p.id = program_id and p.user_id = (select auth.uid())));

-- The prescription of a session is frozen once given; a session recorded before W-1 can be attached
-- once to a program (null → program), never moved to another one.
create or replace function public.workout_sessions_prescription_immutable() returns trigger
language plpgsql set search_path = '' as $$
begin
  if old.program_id is not null and new.program_id is distinct from old.program_id then
    raise exception 'workout_sessions: a session cannot move to another program' using errcode = 'check_violation';
  end if;
  if old.prescription_source is not null and new.prescription_source is distinct from old.prescription_source then
    raise exception 'workout_sessions: prescription_source is immutable' using errcode = 'check_violation';
  end if;
  if old.prescribed_at is not null
     and (new.session_index, new.scheduled_for, new.focus, new.planned_minutes, new.purpose, new.prescribed_at)
         is distinct from
         (old.session_index, old.scheduled_for, old.focus, old.planned_minutes, old.purpose, old.prescribed_at) then
    raise exception 'workout_sessions: a prescribed session is immutable' using errcode = 'check_violation';
  end if;
  -- The adaptation of the day is settled once the session is over.
  if old.status in ('completed', 'skipped', 'replaced', 'rescheduled', 'superseded')
     and (new.adapted_minutes, new.adaptation_reason) is distinct from (old.adapted_minutes, old.adaptation_reason) then
    raise exception 'workout_sessions: the adaptation of a past session is immutable' using errcode = 'check_violation';
  end if;
  return new;
end;
$$;

create trigger workout_sessions_prescription_immutable before update on public.workout_sessions
  for each row execute function public.workout_sessions_prescription_immutable();

-- ---------------------------------------------------------------------------
-- 3. Prescribed exercises (new, immutable)
-- ---------------------------------------------------------------------------

create table public.planned_exercises (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  session_id uuid not null references public.workout_sessions (id) on delete cascade,
  -- The full prescription and each adaptation of the day keep their own rows.
  variant text not null check (variant in ('full', 'short', 'light')),
  position smallint not null check (position between 0 and 30),
  exercise_id text not null check (exercise_id ~ '^[a-z0-9_:-]{1,64}$'),
  sets smallint not null check (sets between 1 and 10),
  reps_min smallint not null check (reps_min between 1 and 300),
  reps_max smallint not null check (reps_max between 1 and 300),
  unit text not null check (unit in ('reps', 'seconds')),
  rest_seconds smallint not null check (rest_seconds between 0 and 600),
  target_rpe numeric(3, 1) check (target_rpe between 1 and 10),
  -- Proposed load; null when the engine had nothing to base it on (never guessed).
  target_load_kg numeric(6, 2) check (target_load_kg between 0 and 1000),
  progression_action text check (progression_action in ('increase_load', 'add_reps', 'keep', 'deload', 'first_time')),
  progression_reason text check (progression_reason ~ '^[a-z0-9_.]{1,80}$'),
  -- Why this exercise is here (structured) and what it targets (muscle, pattern or exercise id).
  purpose text not null check (purpose in (
    'strength', 'hypertrophy', 'muscular_endurance', 'technique', 'maintenance', 'recovery', 'progression'
  )),
  purpose_target text check (purpose_target ~ '^[a-z0-9_]{1,40}$'),
  prescribed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (session_id, variant, position),
  check (reps_max >= reps_min),
  check (progression_reason is null or progression_action is not null)
);

create index planned_exercises_session_idx on public.planned_exercises (session_id);
create index planned_exercises_sync_idx on public.planned_exercises (user_id, updated_at);

create or replace function public.planned_exercises_immutable() returns trigger
language plpgsql set search_path = '' as $$
begin
  -- An identical upsert (a second device pushing the same row) is accepted; any change is refused.
  if (to_jsonb(new) - 'updated_at') is distinct from (to_jsonb(old) - 'updated_at') then
    raise exception 'planned_exercises: a prescription is immutable' using errcode = 'check_violation';
  end if;
  return new;
end;
$$;

create trigger planned_exercises_immutable before update on public.planned_exercises
  for each row execute function public.planned_exercises_immutable();

-- A prescription can only point to a session of the same user.
create policy planned_exercises_own_session on public.planned_exercises as restrictive for all to authenticated
  using (exists (select 1 from public.workout_sessions s where s.id = session_id and s.user_id = (select auth.uid())))
  with check (exists (select 1 from public.workout_sessions s where s.id = session_id and s.user_id = (select auth.uid())));

-- ---------------------------------------------------------------------------
-- 4. What was done: sets and replacements linked to the prescription
-- ---------------------------------------------------------------------------

alter table public.exercise_logs
  add column planned_exercise_id uuid references public.planned_exercises (id) on delete set null;
alter table public.exercise_logs add constraint exercise_logs_reps_or_seconds
  check (reps is null or seconds is null);
create index exercise_logs_planned_idx on public.exercise_logs (planned_exercise_id);

create policy exercise_logs_own_prescription on public.exercise_logs as restrictive for all to authenticated
  using (planned_exercise_id is null or exists (select 1 from public.planned_exercises p where p.id = planned_exercise_id and p.user_id = (select auth.uid())))
  with check (planned_exercise_id is null or exists (select 1 from public.planned_exercises p where p.id = planned_exercise_id and p.user_id = (select auth.uid())));

alter table public.exercise_substitutions
  add column planned_exercise_id uuid references public.planned_exercises (id) on delete set null;
alter table public.exercise_substitutions drop constraint if exists exercise_substitutions_reason_check;
-- Same list as REPLACEMENT_REASONS (src/domain/training/replacement.ts).
alter table public.exercise_substitutions add constraint exercise_substitutions_reason_check check (reason in (
  'dislike', 'cant_do', 'no_equipment', 'easier', 'harder',
  'busy_equipment', 'discomfort', 'too_hard_today', 'no_time', 'preference', 'other'
));
create index exercise_substitutions_planned_idx on public.exercise_substitutions (planned_exercise_id);

create policy exercise_substitutions_own_prescription on public.exercise_substitutions as restrictive for all to authenticated
  using (planned_exercise_id is null or exists (select 1 from public.planned_exercises p where p.id = planned_exercise_id and p.user_id = (select auth.uid())))
  with check (planned_exercise_id is null or exists (select 1 from public.planned_exercises p where p.id = planned_exercise_id and p.user_id = (select auth.uid())));

-- ---------------------------------------------------------------------------
-- 5. Adaptation decisions: a proposal can be postponed (end-of-cycle light week: accept, decline
--    or later). Decisions still go through the existing Adaptation Engine (D-028).
-- ---------------------------------------------------------------------------

alter table public.adjustments drop constraint if exists adjustments_status_check;
alter table public.adjustments add constraint adjustments_status_check
  check (status in ('proposed', 'applied', 'declined', 'reverted', 'postponed'));

-- ---------------------------------------------------------------------------
-- 6. RLS for the new tables (owner only, nothing for anon)
-- ---------------------------------------------------------------------------

do $$
declare
  t text;
begin
  foreach t in array array['training_programs', 'planned_exercises'] loop
    execute format('create trigger set_updated_at before update on public.%I for each row execute function public.set_updated_at()', t);
    execute format('alter table public.%I enable row level security', t);
    execute format('create policy %I on public.%I for select to authenticated using ((select auth.uid()) = user_id)', t || '_select_own', t);
    execute format('create policy %I on public.%I for insert to authenticated with check ((select auth.uid()) = user_id)', t || '_insert_own', t);
    execute format('create policy %I on public.%I for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)', t || '_update_own', t);
    execute format('create policy %I on public.%I for delete to authenticated using ((select auth.uid()) = user_id)', t || '_delete_own', t);
    execute format('revoke all on public.%I from anon', t);
    execute format('grant select, insert, update, delete on public.%I to authenticated', t);
  end loop;
end;
$$;

-- ---------------------------------------------------------------------------
-- 7. History recorded before W-1: attach it to a "reconstructed" program
-- ---------------------------------------------------------------------------
-- Idempotent and safe to call from every device: one reconstructed program per user (unique
-- index), sessions attached once. Nothing is invented: the program has no parameters and the
-- sessions get prescription_source = 'unknown' and no planned_exercises. Their sets, outcomes and
-- replacements are kept as they are. Runs with the caller's rights (RLS applies).
create or replace function public.attach_reconstructed_training_history() returns uuid
language plpgsql security invoker set search_path = '' as $$
declare
  uid uuid := (select auth.uid());
  program uuid;
  first_day date;
begin
  if uid is null then
    raise exception 'not authenticated' using errcode = 'insufficient_privilege';
  end if;

  select min(coalesce(s.scheduled_for, s.created_at::date)) into first_day
  from public.workout_sessions s
  where s.user_id = uid and s.program_id is null and s.prescription_source is null and s.deleted_at is null;

  select p.id into program from public.training_programs p where p.user_id = uid and p.source = 'reconstructed';
  if first_day is null then
    return program;
  end if;

  if program is null then
    insert into public.training_programs (user_id, lineage_id, version, source, status, reason_key, effective_from)
    values (uid, gen_random_uuid(), 1, 'reconstructed', 'ended', 'program.reason.reconstructed', first_day)
    on conflict (user_id) where source = 'reconstructed' do nothing
    returning id into program;
    if program is null then
      select p.id into program from public.training_programs p where p.user_id = uid and p.source = 'reconstructed';
    end if;
  end if;

  update public.workout_sessions s
  set program_id = program, prescription_source = 'unknown'
  where s.user_id = uid and s.program_id is null and s.prescription_source is null;

  return program;
end;
$$;

revoke all on function public.attach_reconstructed_training_history() from public, anon;
grant execute on function public.attach_reconstructed_training_history() to authenticated;
